#! /bin/sh
# vim:fileencoding=utf-8:ft=sh:foldmethod=marker

# {{{ Hotkeys & Windows

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d Home Web Learn Chat Vm Misc

# }}}

# {{{ Bspc Configs

bspc config border_width         2
bspc config window_gap           8
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#3A3F4B"
bspc config normal_border_color "#3A3F4B"

# }}}

# {{{ Bspc Rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a discord desktop="^5"
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Microsoft-edge-beta desktop='^2' follow=on
bspc rule -a Zathura state=tiled desktop="^3" follow=on
bspc rule -a Screenkey manage=off

# }}}

# {{{ Autostart

# 2bspwm &
doas rm -f /var/lib/NetworkManager/NetworkManager.state
doas sv restart NetworkManager
thunar --daemon &
feh --bg-scale ~/Pictures/uwall1.jpg &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xrdb -merge .Xresources &
xbacklight -set 20
nm-applet &
dunst &
doas rfkill unblock wifi
picom --config .config/picom/ash.conf --experimental-backends

# }}}
